[gcp_service_account]
type = "service_account"
project_id = "sale-dashboard-467918"
private_key_id = "d0aad56851ef4c18f60d2f7bdb270ead285019ea"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCbpIvntSBbBp/Q
N/FL84kt3zXf9w3cNrFinTTvCb4NbGMxMjiRuWltXJTw+5i3KtgtjaIdE3M3J/bV
AuYdauKrvMcdBmu7io0JM7LRBtNIEFiVb8wtX1M3s7XRgvUo3vtLEhj0dAMPfVvu
ENK15vCYPb2S2aKvmTbZ5iZpZCcTf0rHfx/OTbWfYLMdtSzF0dakdjMwXvBlceR0
54nlSb1coTzejpADXV7anTPaPDa9GGu/ruluR34YNSDyucU/FInWzhhSTH4lEEFu
3o9z3VnENiQXnIfXOr7T4o40XlhAJ65CcEDYHHOo2Uhcfhc/VvvZEnU8ksmGuozM
+NNgeT9rAgMBAAECggEAND/0G7ApkYVSx0LQhY/XQIgLfQliJMhTmmhuKcUagUUe
s5hJd1pIM0d+VLwR04PVmM1QW/R4nE6VRYM4ny2PtNml+m96YTYtDKbHY/annSyn
oFssrxquRCfXZONSzAq3T8dei0oa8OtDnlMVea1ynZk0eAUJ4WtNB6+Eu6K8n4V5
HkrzYG2sdbUFFdrZ5bGatTqxANldZFU8Wcx8Ug6U+vAKH0CKCZvcKz8qtPYWHHZu
Yg4RrHom2qHfMCg+klFSYakthshynvn5reVGCopc/q+G0ITlEUB6fcQT1pI/fuxw
iAAxZbhnZGWQFzLBJ3pmJ1rxLnfDbUKgB4BNv8zNWQKBgQDIPuN8cfdEi7T7lITk
pfdfA2uC/tLOBCfTmFZNdB8BdGO9qfT/wuTtTL+YlIxouHSQLMEUxJ0bigrxJ7a7
PzBXchAvNodLmhVshsVzFDLawK/CI0AeCEObZjVV1W1S6ou7ZBVBvLGTlZ4Vgu8Z
SsRwhOCV9MuhJ/4jTpa7rtW2lQKBgQDG+nPBG+7Hg9ilMwOsPpPqIKuq1bOTtHdz
BWY9hJOedmUdwIBeWBGzpPtuAeAgpkFooSeGOxqY3L6pevDPEbUEXMPI1MTMD6gD
BVzd9hPmIUWNt2SBSbGeBU7nnFHLmGxCf8Vd3s8JBiE7wQgyyn2mjEdGoAZXbNON
aXs5GWOd/wKBgBhwBFclmWWWHyosv+MflgbUZgSAkL1vqGScTLv7FeWZjKqS2UF1
SXbkTOWUC2akTCVkMNQWAo5f1GIF1LkZRw8E7pC0eOJzFXY/JE2dA2/K4CgzIRoJ
LCcE3DFzcHoUAaWG20lAe/Nk6Pv7FK7jfwG0Vaw3SbqLJOquJpsVBSPZAoGBAISR
uS2f/qbPIThvlLLdvo7u1XEskEiIpEzt/ABgpDmfiB8acmxpIOIfuaTBeyJFoq6j
MEIufrn52M3yKx7LHV+arpbPq46Jn9bja8w2d2uMH1scJMo+3yf5QWjurVCIbRih
KE4ydJ3+h4XYRi4Q20Zrj9FuLMtypkBBVufkEorhAoGBAIU/cAUNa6Y9tR/VPAnZ
QgRTl0y4f6rg8UIi+6ziZoFMmFXS/g0vLMiYw1ObBM4xtKP4C5CLi0yudi7VrxlZ
BRce11yDvQTFTLC+EAdlgVf8q3UuFOZfoHkqhuYfcS2j9Th0/rwaMBSpQtlxrsxo
louVQxm39LzMj+zYptRoj8gT
-----END PRIVATE KEY-----"""
client_email = "saledashboardserviceaccount@sale-dashboard-467918.iam.gserviceaccount.com"
client_id = "100815903271953608747"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/saledashboardserviceaccount%40sale-dashboard-467918.iam.gserviceaccount.com"
universe_domain = "googleapis.com"